### ISSUE TITLE
Unconventional Basic Block Termination and nop Instruction Placement in Binary

### ISSUE THREAD

**Issue by akulpillai** [angr/angr-management#1106]
### Description

![Screenshot 2023-10-19 at 5 30 21 PM](https://github.com/angr/angr-management/assets/32793567/74e75fb4-4b47-4e67-a54c-d00e68da5f02)

In this binary, at addresses `0x401104` and `0x40111c` among others, basic blocks don't conclude with a conditional branch or any control flow instruction and instead end with a `nop` instruction.

Why is the `nop` instruction positioned as such, rather than in the subsequent basic block?

Doesn't this deviate from the conventional definition of a basic block?

### Steps to reproduce the bug

Load the binary using default analysis and configuration.
[chattr_mips-pc-linux_Os.zip](https://github.com/angr/angr-management/files/13047994/chattr_mips-pc-linux_Os.zip)

### Environment

Bundled release of commit: 164635168194e06a162539cae31fed9b14a7914b

**Comment by rhelmot** [comment]
branch delay slots are part of the MIPS architecture and the instructions that fill them are traditionally placed in the block of code coming before them because they happen before the control flow transitions.

**Comment by akulpillai** [comment]
I see, thank you for the quick response!
