### ISSUE TITLE
CodeEdit(?) Source code views don't respect theme colours

### ISSUE THREAD

**Issue by agnosticlines** [angr/angr-management#1127]
### Description

If you switch your theme to any other than the default Light one several elements in the UI still keep their light theme

Function Info:
![6VsOio7BZ0](https://github.com/angr/angr-management/assets/23334509/cc6e36b4-751a-4ee0-b47d-1945e23422af)

Decompiled Code
![fkSJGVvi8d](https://github.com/angr/angr-management/assets/23334509/4c178a40-5ddc-40a8-a842-0de5581a4aec)

There's probably more, seems to be anything that uses the `QCodeEdit` syntax highlighter

### Additional context

Whoops, I was searching for theme issues on the angr repo, not on angr-management, just seen this is a dupe, but there is more sections than that issue mentions that are affected so not sure if I should close/delete this one or not

**Comment by ltfish** [comment]
Just curious: Do they stay white after you restart angr management?

**Comment by mborgerson** [comment]
Dup #847
