### ISSUE TITLE
Custom Toolbar Buttons

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#121]
While you're redoing the plugin system anyway... there's no way for a plugin to add a toolbar button. Right now, the `QToolBar` is created on the fly, added, and then returned but there's no way to access that returned object. I simply cached that object in the `Toolbar` class in my fork [(diff here)](https://github.com/angr/angr-management/compare/master...sraboy:chess_dev).

Unfortunately, I can't push that upstream... because rules and such.

**Comment by ltfish** [comment]
@rhelmot let's make this happen in the new plugin refactor.

**Comment by rhelmot** [comment]
it'll happen. I'm going to add the constraint that you have to declare all the buttons that you want to set up statically, same with toolbar menu items. That way it won't be possible for the plugin to fail to tear the buttons/items down.

**Comment by rhelmot** [comment]
just implemented an interface such that the plugin can declare a toolbar button as follows:

```
class MyPlugin(BasePlugin):
    TOOLBAR_BUTTONS = [(QIcon('/home/audrey/pics/duck-square.png'), 'quack quack motherfuckers')]
    def handle_click_toolbar(self, idx):
        print('quack quack', idx)
```

**Comment by sraboy** [comment]
`'quack quack motherfuckers'` indeed!
