### ISSUE TITLE
Plugin enabled checkboxes are almost invisible in dark mode

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#1210]
### Description

When in dark mode, the checkboxes are nearly invisible. <img width="520" alt="image" src="https://github.com/angr/angr-management/assets/1341797/36a9795c-5774-4957-885c-5f082356fd56">

**Comment by mborgerson** [comment]
Duplicate #916

**Comment by twizmwazin** [comment]
Whoops, my bad
