### ISSUE TITLE
FUNC_COLUMNS IndexError

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#123]
I'm in the middle of migrating to this new plugin architecture and keep hitting this error:

```
  File "<snip>/angrmanagement/plugins/plugin_manager.py", line 187, in get_func_column
    return plugin.FUNC_COLUMNS[idx]
IndexError: list index out of range
```

At the moment, I'm not doing anything with the functions view.

EDIT: I'm guessing the conditional there should be `>=` not just `>`:
`if idx >= len(plugin.FUNC_COLUMNS):`.

**Comment by rhelmot** [comment]
you're right! I am not used to writing boundary conditions for things that look like that!
