### ISSUE TITLE
QInstruction Click Handler Bugs

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#124]
1) Typo: `handle_insn_click` vs `PluginManager.handle_click_insn`
2) Also, the conditionals here consume the click event if it's just a normal left-click, so the plugins are never called. I use every selection of an address to track user activity, telemetry-style, so I can't rely on `InfoDock.selected_insns` (which doesn't tell me which was just clicked, just all of which are currently selected; it also doesn't give me right clicks).

https://github.com/angr/angr-management/blob/be2ae29279f75b8c057fbad5af0d80d468852059/angrmanagement/ui/widgets/qinstruction.py#L68

**Comment by rhelmot** [comment]
I saw in your fork a commit that added an attribute to the am_event for updating selected_insns to say which instruction in particular was clicked. That would be okay to add.

idk how I feel about giving plugins the ability to override the default behavior for normal left and right clicks

**Comment by rhelmot** [comment]
generally I support adding whatever metadata you like to am_events to support whatever behavior you want or could possibly foresee. all the callbacks are supposed to take kwargs for a reason!

**Comment by sraboy** [comment]
Totally forgot I did that. PR inbound!
