### ISSUE TITLE
Segfault on PySide 6.7.0, Python 3.12.0

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#1243]
### Description

Traced to an issue with metaclasses in libshiboken on Python 3.12. Added context on existing issue filed on Qt https://bugreports.qt.io/browse/PYSIDE-2676

**Comment by ltfish** [comment]
An out-of-bound write… good finding!

**Comment by mborgerson** [comment]
Fixed in PySide6==6.7.1
