### ISSUE TITLE
state.inspect.b 

### ISSUE THREAD

**Issue by OMRI-FRX** [angr/angr-management#1269]
### Description

After setting the register read and write breakpoint, when outputting status information in the processing function, it was found that the output information address did not match the instruction address.
![QQ图片20240607015632](https://github.com/angr/angr-management/assets/42199614/7a0f6104-7da9-4dd7-b644-bd69e8f5dad9)

![QQ图片20240607015536](https://github.com/angr/angr-management/assets/42199614/d7b4e9af-b1c9-4f4e-8f05-b8351fe796d3)
![QQ图片20240607015657](https://github.com/angr/angr-management/assets/42199614/20982517-d02c-453a-be9d-14d2b021e6cd)

### Steps to reproduce the bug

[1.zip](https://github.com/user-attachments/files/15672211/1.zip)

**Comment by rhelmot** [comment]
This is due to the fact that angr processes whole basic blocks at a time. Not all locations are updated granularly per-instruction, as it would slow things down.
