### ISSUE TITLE
AttributeError: module 'angr.analyses.cfg' has no attribute 'CFGBase'

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr-management#128]
I searched multiple issues, but couldn't find the matching one.

> (angr) [r668v698@themata angr-management]$ python start.py 
> /Ruturaj/angr/angr/lib/python3.7/site-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
> Traceback (most recent call last):
>   File "start.py", line 30, in <module>
>     main(args.binary)
>   File "/Ruturaj/angr/angr-management/angrmanagement/__main__.py", line 79, in main
>     main_window = MainWindow()
>   File "/Ruturaj/angr/angr-management/angrmanagement/ui/main_window.py", line 81, in __init__
>     self._init_workspace()
>   File "/Ruturaj/angr/angr-management/angrmanagement/ui/main_window.py", line 235, in _init_workspace
>     wk = Workspace(self, Instance())
>   File "/Ruturaj/angr/angr-management/angrmanagement/data/instance.py", line 31, in __init__
>     self.register_container('cfg_container', lambda: None, Optional[angr.analyses.cfg.CFGBase], "The current CFG")
> AttributeError: module 'angr.analyses.cfg' has no attribute 'CFGBase'

I tried to uninstall and reinstall the supported modules. Thanks in advance for your help.

**Comment by twizmwazin** [comment]
It looks like you are using angr from pypi and not from git. Generally speaking, the master branch of an angr-related repo depends on its angr-related dependencies also being installed from master. We have a set of scripts that make this pretty easy to manage: https://github.com/angr/angr-dev.

**Comment by Ruturaj4** [comment]
@twizmwazin thanks for your reply, but I solved this by - changing -

>  self.register_container('cfg_container', lambda: None, Optional[angr.analyses.cfg.CFGBase], "The current CFG")

to

> self.register_container('cfg_container', lambda: None, Optional[angr.analyses.cfg.cfg_base.CFGBase], "The current CFG")

**Comment by twizmwazin** [comment]
If you continue using angr-management from master, do expect things to break over time with little or no warning. We will add new features to angr and friends, and we do not wait for a release on pypi before using those changes in downstream projects like angr-management. Soon we will have nightly builds of angr-management that come with all the dependencies packed in, which should simplify the setup for new users, but that is not yet complete.

**Comment by ltfish** [comment]
The related commit in angr (which does not exist in the PyPI version yet): https://github.com/angr/angr/commit/2a3bd28e69ac13d1a9dd8fc762d2aebbc32cd62f
