### ISSUE TITLE
Unable to create New States for symbolic execution

### ISSUE THREAD

**Issue by PatDevNet** [angr/angr-management#1316]
### Description

I'am unable to create New States for symbolic execution in angr-management, when i press New State and Ok (accepting all default settings) the state did not appear on the list. I've already tried this in Ubuntu 20 and 22 using yours zip archive for v9.2.116 and v9.2.15 and on Kali Linux 2024 . I tried also on python virtual env - still have the same issue. 

![image](https://github.com/user-attachments/assets/e65e7b81-ad43-4b70-a53f-c6ac8bfa4abf)

### Steps to reproduce the bug

Installation on Ubuntu 20, 22 and Kali linux, Windows 11, using two last version from github.

**Comment by PatDevNet** [comment]
Do you mean options to find execution and avoid execution? I created both and checked in simulation Manager. 
Where should i add/fix missing args ?

**Comment by twizmwazin** [comment]
I followed your instructions and was able to reproduce the issue, and it should be fixed on master now. Download the latest nightly from the releases page, give it a try and let me know if the issue persists or you find any further issues.

**Comment by PatDevNet** [comment]
It is working on Ubuntu 22 with angr management nightly preview (9.2.117.dev0). Thank you.
I really appreciate quick response. 
On Windows it is possible to create New State, but after "Explore" there is some issue in logs:

ERROR | 10:08:11 | angrmanagement.data.object_container | Error raised from event of (container: Active simulation manager)(container: lawful brush-tailed bettong)<SimulationManager with 2 deadended>
Traceback (most recent call last):
  File "angrmanagement\data\object_container.py", line 34, in am_event
  File "angrmanagement\ui\widgets\qpathtree.py", line 146, in _watch_simgr
  File "angrmanagement\ui\widgets\qpathtree.py", line 46, in reload
  File "angrmanagement\ui\widgets\qpathtree.py", line 138, in _generate_graph
  File "angrmanagement\ui\widgets\qstate_block.py", line 42, in __init__
  File "angrmanagement\ui\widgets\qstate_block.py", line 55, in _init_widgets
ReferenceError: weakly-referenced object no longer exists

P.S. It is not possible to change Simulation Manager. On Ubuntu is another one : Tan Glider - and there everything is working fine.

**Comment by twizmwazin** [comment]
This may be related to your issues: https://github.com/angr/angr-management/pull/1319

Still looking into what the weakly-referenced object issue is about, something is getting dropped prematurely
