### ISSUE TITLE
[Solution found, add to documentation?] Missing window top bar in GNOME Wayland

### ISSUE THREAD

**Issue by dariox86** [angr/angr-management#1321]
EDIT: I just found a solution: instead of QT_QPA_PLATFORM=wayland I need to set QT_QPA_PLATFORM=**wayland-egl**. Perhaps a disclaimer in a FAQ or something could help someone else with the same issue.

### Description

On Parabola GNU/Linux-libre with GNOME on Wayland session, the top bar of the application is missing. Running the application with XWayland the top bar is shown as expected. I am filing this as a feature request because even though this could be an issue on my end that could be fixed with some tinkering, other Qt 6 applications work out of the box.

![angr-management](https://github.com/user-attachments/assets/4caaf752-0bff-46f6-9ba9-0582ce73e940)

### Alternatives

On Ubuntu 24.04 it works out of the box, but on my environment this may need some tinkering to make it work.

### Additional context

I carried out several tests with packages from every distribution up to date as of this writing with angr Management v9.2.117 for Ubuntu 22.04.

Parabola GNU/Linux-libre with GNOME, Wayland session, Wayland packages for Qt 5 and Qt 6 installed
```
$ export QT_QPA_PLATFORM=wayland
$ ./angr-management
```
Missing title bar (see picture above).

```
$ export QT_QPA_PLATFORM=xcb
$ ./angr-management
```
It works as expected with the title bar.

-

Ubuntu 24.04 with GNOME, Wayland session, Wayland packages for Qt 5 and Qt 6 installed
```
$ export QT_QPA_PLATFORM=wayland
$ ./angr-management
```
It works as expected with the title bar.

```
$ export QT_QPA_PLATFORM=xcb
$ ./angr-management
```
It works as expected with the title bar.

-

Ubuntu 22.04 with GNOME, Wayland session, Wayland packages for Qt 5 and Qt 6 installed
```
$ export QT_QPA_PLATFORM=wayland
$ ./angr-management
```
«Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: wayland-egl, linuxfb, minimal, offscreen, wayland, xcb, vkkhrdisplay, minimalegl, eglfs, vnc.
Aborted»

```
$ export QT_QPA_PLATFORM=xcb
$ ./angr-management
```
It works as expected with the title bar.

-

openSUSE Tumbleweed with KDE Plasma, Wayland session, Wayland packages for Qt 5 and Qt 6 installed
```
$ export QT_QPA_PLATFORM=wayland
$ ./angr-management
```
It works as expected with the title bar.

```
$ export QT_QPA_PLATFORM=xcb
$ ./angr-management
```
It works as expected with the title bar.

**Comment by twizmwazin** [comment]
We've had other issues with this before, eg https://github.com/angr/angr-management/issues/1268. At some point we will want to make sure that angr management works properly on wayland. For now, whenever someone has an issue I just instruct them to use X11 for the time being, which I understand is not an option at worst and sub-optimal at best.

**Comment by dariox86** [comment]
Now it works with QT_QPA_PLATFORM=wayland as expected.
