### ISSUE TITLE
Increasing font size of decompiled code applies inconsistently

### ISSUE THREAD

**Issue by adamdoupe** [angr/angr-management#177]
You can increase the font size (on MacOS) of the windows by using cmd-scroll wheel.

This works on the disassembly view, however the decompiled code view does not increase the font size consistently:
<img width="1070" alt="Screen Shot 2020-05-01 at 10 44 52 AM" src="https://user-images.githubusercontent.com/48102/80827876-44dfdb80-8b99-11ea-847e-466350e7b844.png">

**Comment by ltfish** [comment]
It's fixed as of a long time ago.
