### ISSUE TITLE
Console and Components dock-widgets dont dock 

### ISSUE THREAD

**Issue by flobotics** [angr/angr-management#194]
hi,
when i open angr-management the "Components" dock is floating .

I found out now, that both (Console and Components) are dockable beside the "Functions"-dock, and the "Console" dock also, but not at the top or botton. Also not inside where the other widgets are like "Disassembly" and so are tabbed?

If e.g. the floating console dock disappears (ts hard to get it "appearing/visible" again.

If i close a dock-widget, its impossible to re-open it again, or?

thx

**Comment by mborgerson** [comment]
Should be fixed now

**Comment by flobotics** [comment]
thanks
