### ISSUE TITLE
Support running behind socks proxy for network requests

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#239]

**Comment by rhelmot** [comment]
What network requests did we have trouble with? The only network activity I can find in the code uses `requests`, which should automatically pull http and socks proxies to use out of the environment.

**Comment by twizmwazin** [comment]
The necessary dependencies for socks proxies are not installed in the distributable builds. I will get them added and then see about testing it.

**Comment by twizmwazin** [comment]
Fixed in 29198be1849e582e2bc2a2e546db6f882355dbb3
