### ISSUE TITLE
Views cannot be re-opened once closed

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#267]
With exception of the disassembly view (which is broken on re-open, #266), a closed view cannot be re-opened. Ideally these should be accessible from the main menu <kbd>View</kbd>.

**Comment by rhelmot** [comment]
One thing contributing to this problem is that pretty much nobody unsubscribes from objectcontainers when they're closed, so you end up with errors like `RuntimeError: Internal C++ object (PySide2.QtWidgets.QComboBox) already deleted.`

**Comment by rhelmot** [comment]
I pushed some fixes for this. What else do you think is essential to be able to reopen?
