### ISSUE TITLE
migration to pyside2

### ISSUE THREAD

**Issue by crowell** [angr/angr-management#28]
qt5 is stable and used by most modern linux distributions as the default. pyside is for qt4, and isn't compatible with qt5. pyside2 is for usage with qt5.

https://wiki.qt.io/PySide2

**Comment by ltfish** [comment]
Actually this is in my plan, especially for several great features about MainWindow coming along with Qt 5.6. I'm simply waiting until PySide2 is pip installable!

**Comment by ltfish** [comment]
Update: This will happen as soon as PySide2 is installable from PyPI, which will happen within the next few weeks or months. I've been closely monitoring PySide2's progress.

**Comment by daniellimws** [comment]
Seems like they released it 6 days ago https://pypi.org/project/PySide2/

Or you guys do not want the dev version?

**Comment by ltfish** [comment]
No cp27+windows support :/

**Comment by ltfish** [comment]
The ultimate solution: Migrating angr to Python 3.

**Comment by ltfish** [comment]
It is done. Close.
