### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MIPS_GRP_CALL'

### ISSUE THREAD

**Issue by frapik99** [angr/angr-management#29]
Hi all,
I have loaded an example project and double clicked on one symbol but I had the following error:

```
AttributeError: 'module' object has no attribute 'MIPS_GRP_CALL'
```

How can I fix it? Any problem with capstone?

**Comment by ltfish** [comment]
https://github.com/angr/angr-management/blob/master/README.md

Scroll to the bottom :-)

**Comment by frapik99** [comment]
PEBCAK :)
