### ISSUE TITLE
Structs view (and a centralized manner of managing custom structs)

### ISSUE THREAD

**Issue by ltfish** [angr/angr-management#298]

**Comment by rhelmot** [comment]
my opinion: the UI should be totally modeled after the IDA "local types" view.

**Comment by rhelmot** [comment]
Maybe better: the binary ninja types view, with the IDA type editor view.

**Comment by mborgerson** [comment]
It would be nice if you could double-click on a printed struct and it showed an editing widget inline that allows you to change the struct definition (instead of opening a popup)

**Comment by rhelmot** [comment]
I didn't hit all our goals for this issue but we have something functional. I'm gonna close this and we can open more issues if we decide we want more features in the future. The main feature we need for parity with IDA is struct offsets in the struct editor. I am not that excited about the possibility of having an inline editor, based on how difficult it was to wrangle qt into behaving for the basic thing we have right now.

Oh, and someone needs to test the structs view on a highdpi display. I suspect there will be problems.
