### ISSUE TITLE
Under simplification of SSA variables in Decompilation

### ISSUE THREAD

**Issue by mahaloz** [angr/angr-management#350]
Decompilation of simple functions, usually including some kind of indirect call, cause `Decompiler` to not simplify use of single assigned `tmps`. Here is the source;
```c
void indirect_caller(void (*func_ptr)(int, int), int a, int b)
{
    (*func_ptr)(a, b);
}
```

Here is the decompilation:
[indirect_calls.zip](https://github.com/angr/angr-management/files/6737063/indirect_calls.zip)

```c
int indirect_caller(BOT a0, unsigned long long a1, unsigned long long a2)
{
    BOT tmp_30;  // tmp #30
    BOT tmp_34;  // tmp #34
    BOT tmp_38;  // tmp #38
    BOT tmp_40;  // tmp #40
    BOT tmp_39;  // tmp #39
    BOT tmp_43;  // tmp #43
    BOT tmp_42;  // tmp #42
    unsigned long long v0;  // [bp-0x20]
    unsigned int v1;  // [bp-0x18]
    unsigned int v2;  // [bp-0x14]
    BOT v3;  // [bp-0x10]
    BOT v5;  // rax
    unsigned long long v6;  // rcx
    unsigned long long v7;  // rdx
    unsigned long long v8;  // rsi
    unsigned long long v9;  // rdi

    v3 = a0;
    v2 = (int)a1;
    v1 = (int)a2;
    tmp_30 = (long long)a2;
    v6 = a2;
    tmp_34 = (long long)a1;
    v7 = a1;
    tmp_38 = v3;
    tmp_40 = (int)tmp_30;
    tmp_39 = (long long)tmp_40;
    v8 = tmp_39;
    tmp_43 = (int)tmp_34;
    tmp_42 = (long long)tmp_43;
    v9 = tmp_42;
    v0 = 4196077;
    v5 = tmp_38();
    return rax<8>;
}
```

Attached is the binary.

**Comment by rhelmot** [comment]
The underlying problem here is https://github.com/angr/angr/issues/2683. The simplifier doesn't even think about removing temps yet.

**Comment by mahaloz** [comment]
> The underlying problem here is [angr/angr#2683](https://github.com/angr/angr/issues/2683). The simplifier doesn't even think about removing temps yet.

This is strange, since in an earlier version of angr-management this does not happen.

**Comment by mahaloz** [comment]
closing since this is a duplicate.
