### ISSUE TITLE
Re-color call targets in dark theme and refresh the current disassembly view after switching themes

### ISSUE THREAD

**Issue by tiffanyb** [angr/angr-management#374]
The palette for the dark theme needs to be tuned.

![image](https://user-images.githubusercontent.com/4591194/124522861-7eb5fe80-dda9-11eb-9fe0-5895ef561cab.png)

**Comment by ltfish** [comment]
If you switch to another function and then switch back, this is what you will see:

![image](https://user-images.githubusercontent.com/5071575/124836111-46dcc180-df37-11eb-9ba9-0128c8831a96.png)

Obviously we forgot to refresh the current disassembly view after changing the theme!

The only thing that needs tuning is the color for call targets.
