### ISSUE TITLE
Unable to run angr-management on my Mint linux machine

### ISSUE THREAD

**Issue by syncush** [angr/angr-management#44]
Hi , I am trying to to run angr-management for the first time , I have installed PySide and all qt dependencies successfully (I hope so ) , I ran 
`python2.7 -m angrmanagement`

and got an import error , saying no module named cfb , So I pip installed it 

`pip2.7 install cfb`

And I still get the import error , am I missing something ?

syncush@syncush ~/Desktop/angr-management $ sudo pip2.7 install cfb
The directory '/home/syncush/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cfb
  Downloading cfb-0.8.3-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from cfb)
Installing collected packages: cfb
Successfully installed cfb-0.8.3

syncush@syncush ~/Desktop/angr-management $ python2.7 -m angrmanagement
WARNING | 2018-04-03 18:15:14,230 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/syncush/Desktop/angr-management/angrmanagement/__main__.py", line 72, in <module>
    main()
  File "/home/syncush/Desktop/angr-management/angrmanagement/__main__.py", line 58, in main
    from .ui.main_window import MainWindow
  File "angrmanagement/ui/main_window.py", line 14, in <module>
    from .workspace import Workspace
  File "angrmanagement/ui/workspace.py", line 7, in <module>
    from .views import FunctionsView, DisassemblyView, SymexecView, StatesView, StringsView, ConsoleView
  File "angrmanagement/ui/views/__init__.py", line 2, in <module>
    from .disassembly_view import DisassemblyView
  File "angrmanagement/ui/views/disassembly_view.py", line 8, in <module>
    from ..widgets import QDisasmGraph, QDisasmStatusBar, QLinearViewer
  File "angrmanagement/ui/widgets/__init__.py", line 10, in <module>
    from .qlinear_viewer import QLinearViewer
  File "angrmanagement/ui/widgets/qlinear_viewer.py", line 9, in <module>
    from angr.analyses.cfg.cfb import Unknown
ImportError: No module named cfb

**Comment by rhelmot** [comment]
This is a version mismatch problem. Pip lags behind Github by a few weeks,
so you need to only use code installed from Github with other code
installed from Github. See extremely-simple-setup.sh in the angr-dev repo
for how to install angr from source.

**Comment by syncush** [comment]
While running , extremely-simple-setup.sh I got the following issue , I was hoping that you might have encountered the same : 

Obtaining ~/syncush/Desktop/angr-dev/pyvex
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I know this might not be related to angr at all , but I have tried every top rated suggestion in StackOverflow in order to resolve 

`command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ltfish** [comment]
You don't want to run angr in Python 3. You need Python 2.

**Comment by rhelmot** [comment]
Part of learning to be a good developer is to identify which part of the error message is the important part! In this case it's not gcc failed with exit status 1, but rather, "Python.h - no such file or directory". This means you don't have your operating system's python-dev package installed. However, I'm sure that you did - the overarching problem is that you're running this with python 3, not python 2. angr doesn't work under python 3!

extremely-simple-setup.sh is intended to be a teaching tool. It works as an install script but its real value is you reading it and understanding the actual code structure of angr and how to install it manually.

**Comment by ltfish** [comment]
In general, if you want to use angr management, because of how fast we move and break things (and how slow we are releasing to PyPI), you really want to use a dev-install of angr. Sorry for that.

**Comment by syncush** [comment]
Ty for the support
