### ISSUE TITLE
Disassembly view fails to distinguish memory operand size

### ISSUE THREAD

**Issue by dnivra** [angr/angr-management#492]
For a function, [the graph disassembly view](https://user-images.githubusercontent.com/281957/133704802-1b7b87c0-c744-417b-8230-50b56197c7f8.png) is incomplete: only the first instruction is displayed. [In the graph disassembly view generated using the rest of the function](https://user-images.githubusercontent.com/281957/133704807-c324be28-79ed-4a73-924b-3cc04f05b56d.png), the first block is entirely incorrect. angr displays the disassembly correctly:

```
ipdb> self.state.project.factory.block(0x804e74c).pp()
0x804e74c:      fld     qword ptr [esp + 4]
0x804e750:      fptan
0x804e752:      fnstsw  ax
0x804e754:      sahf
0x804e755:      jp      0x804e75a
```

[On checking the linear disassembly](https://user-images.githubusercontent.com/281957/133704750-cec9bf6a-b3b4-44da-be94-31c6a38e6fc8.png), I found 3 semantically equivalent blocks starting at 0x804e740, 0x804e746 and 0x804e74c respectively. Perhaps the entry block is somehow misidentified as a result? The function where the issue occurs is 0x804e74c in [CROMU_00028](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CROMU_00028). I could try looking into this but unsure where to start investigating; I can try help if given some inputs!

PS: The title is very broad and generic but I couldn't come up with a better one. Feel free to edit it with more details once the reason for this issue is known.

**Comment by mborgerson** [comment]
It looks like there are three different functions variants here, each one supports loading different sized floating point values from the stack, then each jumps to a common block that proceeds to compute tangent of the loaded value. Unfortunately the disassembly view fails to distinguish the differently sized operands.

Disassembly starting at 0x804e740 there are three different loading variants, for extended double precision, single precision, and double precision:

```
0:  db 6c 24 04             fld    TBYTE PTR [esp+0x4]
4:  eb 0a                   jmp    0x10
6:  d9 44 24 04             fld    DWORD PTR [esp+0x4]
a:  eb 04                   jmp    0x10
c:  dd 44 24 04             fld    QWORD PTR [esp+0x4]
10: d9 f2                   fptan
12: df e0                   fnstsw ax
14: 9e                      sahf
15: 7a 03                   jp     0x1a
17: dd d8                   fstp   st(0)
19: c3                      ret
```

The blocks are listed as part of the function at 0x804e740

**Comment by dnivra** [comment]
Ah I see: I thought the 3 blocks were all identical since angr-management's disassembly view doesn't show the size of the memory operand being accessed.

**Comment by ltfish** [comment]
> since angr-management's disassembly view doesn't show the size of the memory operand being accessed.

This is the real bug that is on my radar...
