### ISSUE TITLE
websocket-client, pyzmq, jupyter-client dependencies should be removed

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#525]
These required dependencies are apparently not used.

**Comment by ltfish** [comment]
They were required by the IPython console in angr management. Are they no longer required?

**Comment by mborgerson** [comment]
> They were required by the IPython console in angr management. Are they no longer required?

pyzmq is required for qtconsole, but it's listed as part of qtconsole's requirements. We should not need to specify it as a requirement for angr-management

**Comment by ltfish** [comment]
> pyzmq is required for qtconsole, but it's listed as part of qtconsole's requirements

I added that check because in older versions of qtconsole pyzmq wasn't listed as a requirement.
