### ISSUE TITLE
Pseudocode view 'pseudocode' combo box

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#602]
Intended to select between different pseudocode representations, only one option is available and displayed. This control is currently not useful and should be disabled to avoid user confusion until more than one representation is available.

**Comment by rhelmot** [comment]
If the binary has debug symbols and the source for the function is on the local machine, it will show the option to toggle to the original source code.

**Comment by mborgerson** [comment]
> If the binary has debug symbols and the source for the function is on the local machine, it will show the option to toggle to the original source code.

Oh, nice. I have not used this feature yet. Maybe there is a way we represent this functionality more clearly. Perhaps with a greyed out option to select 'Original Source', or something
