### ISSUE TITLE
`KeyError: 'DW_AT_name'` exception when trying to load binary with debuginfo

### ISSUE THREAD

**Issue by bjorn3** [angr/angr-management#618]
This happened when trying to load the `rustup` binary from `~/.cargo/bin/rustup` as acquired from https://rustup.rs/. This is a binary compiled with rustc. I get neither a popup that it crashed, not an entry in the log. It only shows in the console the following:

```
Exception while running job "Loading file":
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 284, in _worker
  File "angrmanagement/data/jobs/job.py", line 45, in run
  File "angrmanagement/data/jobs/loading.py", line 88, in _run
  File "angr/project.py", line 137, in __init__
  File "cle/loader.py", line 133, in __init__
  File "cle/loader.py", line 668, in _internal_load
  File "cle/loader.py", line 850, in _load_object_isolated
  File "cle/backends/elf/elf.py", line 168, in __init__
  File "cle/backends/elf/elf.py", line 629, in _load_dies
  File "cle/backends/elf/variable_type.py", line 15, in read_from_die
KeyError: 'DW_AT_name'
```

After that the ui doesn't update with the binary I asked angr to load.

Angr-management commit: https://github.com/angr/angr-management/commit/2e407502750ec39ca01c7ac663f3f8ae93399dd6 (prebuilt version from github releases)

**Comment by bjorn3** [comment]
When disabling loading of debuginfo it seems to work. It takes several minutes though for a 16MB binary (10MB `.text`) with the following errors and warnings:

* Unsupported statement type CAS.
* Unsupported Triop lop_Sub64Fx2.
* The program is accessing register with unspecified value. This could indicate unwanted behavior. (i suspect this is the decompiler not being smart enough to know that the register is not accessed when it is uninitialized at runtime)
* Tried to cast_low an interval to an interval shorter than its stride.
* Unsupported Binop Iop_CasCmpNE64.
* Unsupported Binop Iop_MullU64.
* Operation UMUL with condition CondO is not supported in pc_calculate_condition_simple(). Consider implementing.
* Unsupported Unop Iop_GetMSBs8x16.
* Unsupported Binop Iop_InterleaveLO8x16.
* Unsupported Binop Iop_64HLtoV128.
* Unsupported Binop Iop_Add64x2.
* Unsupported Binop Iop_CasCmpNE8.

**Comment by ltfish** [comment]
Thank you. The first one is a bug in CLE. The second is more about the types of internal warning messages that we should hide from GUI users.

**Comment by bjorn3** [comment]
I can confirm that loading it with debuginfo doesn't crash immediatly now. It still uses too much memory for my system, but that is not really a bug in itself I think.

**Comment by ltfish** [comment]
How much memory do you have?

**Comment by bjorn3** [comment]
4GB. I know it is rather little nowadays.

**Comment by ltfish** [comment]
Yeah… there are a lot of things in angr that we want to improve, including RAM usage, but it’s definitely not one of our top priorities.

**Comment by bjorn3** [comment]
Makes sense.
