### ISSUE TITLE
BinNavi as a replacement?

### ISSUE THREAD

**Issue by Manouchehri** [angr/angr-management#7]
I was thinking it might be possible to use [Zynamics' BinNavi](https://github.com/google/binnavi) as a GUI for the CFG. We would have to figure out a way to use [BinExport](https://github.com/google/binexport) to get the graph data from angr's NetworkX.

How feasible do you guys think this is?

https://github.com/google/binnavi/wiki/Replacing-IDA-as-Disassembler-Frontend#alternatives-for-interfacing-a-disassembler-with-binnavi

**Comment by ltfish** [comment]
Thanks for your suggestion. Personally I'd like to keep improving the CFG view from angr-management. I'll take a look at BinNavi first.
