### ISSUE TITLE
Smoke test nightly builds before releasing

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#725]
We've had multiple failures in the past and release frequently break. We need a mechanism to know about this as soon as possible.

**Comment by twizmwazin** [comment]
This is done for linux as of 6751e9831e5758e74f8079f019731ca13e7d4741

**Comment by zwimer** [comment]
@twizmwazin Is this issue now fully complete?

**Comment by twizmwazin** [comment]
Only ubuntu is smoke tested. No testing of any kind exists for Windows or macOS.

**Comment by zwimer** [comment]
It'll spit back 0 characters if nothing exists, and if windows do exists, it just concats all the names. Though the macOS app is not titled...

**Comment by zwimer** [comment]
For example, with 2 windows with 'angr management' open, I get:
```bash
$ osascript -e 'tell application "System Events" to (get name of windows of processes whose name contains "angr management") as string'
Release angr management nightly preview · angr/angr-management - Google Chrome - Zacangr management
```
The two window names are: `Release angr management nightly preview · angr/angr-management - Google Chrome - Zac` and `angr management`

**Comment by zwimer** [comment]
Alternatively, if you are sure the app won't run with the name `Python`: `osascript -e 'tell application "Finder" to get name of every process whose (visible is true and name contains "angr" and name contains "management")'`

**Comment by zwimer** [comment]
Might need this issue to be fixed first: https://github.com/angr/angr-management/issues/827

**Comment by twizmwazin** [comment]
We now smoke test ubuntu, windows, and macOS before releasing nightly builds, further work on this will probably be part of #741
