### ISSUE TITLE
Support font customization

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#744]
### Description

* For accessibility and personalization, add GUI to allow a user to change their fonts.
* IDA has a convenient option in the context-menu for views that gives quick access to changing the fonts. It would be nice to mirror this.

### Alternatives

N/A

**Comment by zwimer** [comment]
Are you referring to changing the default application font? Something like https://stackoverflow.com/questions/42041482/change-default-application-font
But where the font selection is a pane in preferences?
