### ISSUE TITLE
View dock widget mouse origin is off on undock event

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#746]
### Description

After PySide6 update, view dock widgets do not undock correctly. Dragging the view out does not move the window by drag distance, but instead places the view some large distance from current mouse position.

Once undocked, you can click on the undocked widget and drag & dock it as expected.

Unclear if this is a platform-specific issue or not.

### Steps to reproduce the bug

* Open angr-management.
* Attempt to drag a view out by its dock widget title bar.
* The window does not drag relative to current mouse position as expected. It snaps some distance away, sometimes on another monitor for me.

### Environment

Ubuntu 22.04
Version: fba92ac7e276d30c6d70df6d60bcd975a791561e

**Comment by ltfish** [comment]
Are you using a fractional display ratio?

**Comment by ltfish** [comment]
According to https://wiki.qt.io/Qt_for_Python_Development_Notes, `6.4.0.1 will likely to be released next week to include a couple of important fixes in 6.4.0`.

**Comment by mborgerson** [comment]
> Are you using a fractional display ratio?

No but I do have monitors of different sizes (1x4k,2x1080p)



> According to https://wiki.qt.io/Qt_for_Python_Development_Notes, `6.4.0.1 will likely to be released next week to include a couple of important fixes in 6.4.0`.

I managed to upgrade to 6.4.0, with some manual fixes in dependencies and the issue isn't present, so hopefully we can update soon

**Comment by ltfish** [comment]
As soon as 6.4.0.1 is out and a new version of qtpy is updated, we will pin to PySide6 6.4.0.1.
