### ISSUE TITLE
Some views unsubcribe from event handlers multiple times

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#777]
### Description

View cleanup logic should not run multiple times.

```
WARNING | 2022-11-04 16:42:39,623 | angrmanagement.data.object_container | Double-unsubscribe of <bound method QStateTable._watch_states of <angrmanagement.ui.widgets.qstate_table.QStateTable(0x541b440) at 0x7f418604d000>> from (container: Global states list)[]
WARNING | 2022-11-04 16:42:39,804 | angrmanagement.data.object_container | Double-unsubscribe of <bound method QSimulationManagers._watch_simgr of <angrmanagement.ui.widgets.qsimulation_managers.QSimulationManagers(0x538fc50) at 0x7f4186cfbac0>> from (container: Active simulation manager)None
WARNING | 2022-11-04 16:42:39,804 | angrmanagement.data.object_container | Double-unsubscribe of <bound method QSimulationManagers._watch_simgrs of <angrmanagement.ui.widgets.qsimulation_managers.QSimulationManagers(0x538fc50) at 0x7f4186cfbac0>> from (container: Global simulation managers list)[]
WARNING | 2022-11-04 16:42:39,804 | angrmanagement.data.object_container | Double-unsubscribe of <bound method QSimulationManagers._watch_state of <angrmanagement.ui.widgets.qsimulation_managers.QSimulationManagers(0x538fc50) at 0x7f4186cfbac0>> from (container: Selected state)None
```

### Steps to reproduce the bug

* Open angr-management
* Close all open views
* Observe warnings in log

### Environment

001987f3970287837ae370a1f2b68de8bca96951

### Additional context

Related #776

**Comment by zwimer** [comment]
I noticed this log message is printed 3 times if I close "Symbolic Execution" and once if I close "States" specifically.

**Comment by zwimer** [comment]
This issue seems to be that `_on_dock_widget_closed
` invokes the unsubscription as well as something else when these views are closed; where as for other views like `Proximity`, `_on_dock_widget_closed` does not do this.

**Comment by zwimer** [comment]
For `state_view.py` the solution is one of the following:

1. If we should unsubscribe when the view is hidden, we should have the `QStateTable` object resubscribe when the view is shown
2. If we should unsubscribe on close, override `closeEvent` in the view; have it invoke a function in the the `QStateTable` child object which unsubscribes if this doesn't automatically invoke the child closeEvent, which it may not.
3. If we should only unsubscribe when the view is destroyed, we should have `QStateTable`'s `__init__` call `self.destroyed.connect`; note that C++ object itself will have already been removed in C++; so doing anything beyond using will raise RuntimeErrors as it's a dangling by this point; `am_unsubscribe` does not do anything beyond that; it might be worth adding documentation to `am_unsubscribe` that it is safe to use with destroyed objects so future debugging might not confuse others if they notice the reference passed is that.

If closing and destroying are synonymous here, which I suspect, then either will work. I think 3 is cleaner, but there might be a race condition with 3 if someone triggers this event between the destruction and the destruction signal emission.

**Comment by zwimer** [comment]
For `qsimulation_managers.py`, we are being explicit that hiding is the same as destruction here. 
```python
    def hideEvent(self, event):  # pylint: disable=unused-argument
        self.simgr.am_unsubscribe(self._watch_simgr)
        self.simgrs.am_unsubscribe(self._watch_simgrs)
        self.state.am_unsubscribe(self._watch_state)
        return super().destroy()
```

I'm not sure this is intentional, as it means switching away from then back to the view causes the object to be destroyed then possibly could be used after destruction. Given this though, I assume we want to adapt either 2 or 3 from the `state_view.py` suggestions to this.

**Comment by zwimer** [comment]
@rhelmot Which was the intention of the existing code?
https://github.com/angr/angr-management/blob/41b574ed070e8112b1cf5e61e43e81286d569c86/angrmanagement/ui/widgets/qstate_table.py#L77
and
https://github.com/angr/angr-management/blob/41b574ed070e8112b1cf5e61e43e81286d569c86/angrmanagement/ui/widgets/qsimulation_managers.py#L50

**Comment by rhelmot** [comment]
iirc with the old docking system hiding was the only event we got, there was no destruction event. If hiding/destruction is working correctly now, go nuts on fixing it.
