### ISSUE TITLE
Missing Graph Folder

### ISSUE THREAD

**Issue by F4lc0nCt** [angr/angr-management#8]
Hi!

I used pip in order to install angr-management on Debian 8 and when I started it, it told me that the graph module was missing. After doing a hard copy from the Git repository to my computer I coped with this problem. It seems that the problem comes from the [pip package](https://pypi.python.org/pypi/angr-management/4.6.6.15) where the folder ui/graph is missing.

**Comment by ltfish** [comment]
Yep, thanks for spotting this problem! I'll make sure it's fixed in our next release :-)

**Comment by ltfish** [comment]
I just did a push to GitHub, and this issue should be fixed. A new release will be made soon.

**Comment by F4lc0nCt** [comment]
Thank you. This GUI seems to be very convenient.
