### ISSUE TITLE
UI Color Changes Temporary

### ISSUE THREAD

**Issue by zwimer** [angr/angr-management#808]
### Description

Changing colors in the UI via preferences is undone when a theme is changed.

### Steps to reproduce the bug

1. Open preferences
2. Change a color for the current theme
3. Click save.
4. Open preferences
5. Change the theme
6. Click load
7. Change the theme back to the original
8. Click load

You will notice by this point, the color originally saved for this theme is no longer saved.

### Environment

Master

**Comment by rhelmot** [comment]
Not a bug. It would be very unintuitive if you could either a) set colors that didn't change when your theme changed, or b) set colors that edited the theme template. The current behavior, where loading a theme overrides your prior selections, is the best we can do.

**Comment by zwimer** [comment]
@rhelmot Closing in favor of: https://github.com/angr/angr-management/issues/809
