### ISSUE TITLE
Better Keyboard Shortcut for Preferences

### ISSUE THREAD

**Issue by zwimer** [angr/angr-management#810]
### Description

To open preferences, right now on mac it is Command-`p`. This is 'print' on every other app; in windows ctrl-p is also print. We should change this.

We should change it to:
For macOS: Command-`,`
For Windows: TBD
For Linux: TBD

**Comment by zwimer** [comment]
@twizmwazin What does Windows normally use as a shortcut for preferences? On macOS, Command-`,` on most any app will open that app's preferences; it's rather standard like Command-`q` for quit. What is the 'preferences' shortcut for Windows? I assume the same for Linux?

**Comment by twizmwazin** [comment]
Pyside/Qt has [this](https://doc.qt.io/qtforpython/PySide6/QtGui/QKeySequence.html#standard-shortcuts) nifty tables that shows all of the common built-in keyboard shortcut. Only macOS has a standard preferences key.
