### ISSUE TITLE
"Load a new docker target" is shown in file menu even if archr is not installed

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#835]
### Description

In environments without archr, the option "Load a new docker target" is shown in the file menu. This also applies to the pyinstaller bundled version of the program when archr is not bundled.

**Comment by zwimer** [comment]
Actually, is this a bug? Right now it informs the user that docker has to be installed to use this feature rather than just not existing. This was an intentional UI decision iirc. Idk if we want to keep it for certain, but I think this is not a bug for sure.

**Comment by zwimer** [comment]
The same is true with the docker icon in the top bar of the UI.

**Comment by zwimer** [comment]
If we want this, we should make `archr` an optional dependency. So users can do `pip install angr-management[docker]` rather than telling them to pip install arch and keystone-engine with `--no-binary` standalone.

**Comment by twizmwazin** [comment]
We removed the docker button if archr is not installed. pip install instructions aren't valid in pyinstaller builds so the current error message is simply incorrect.

**Comment by zwimer** [comment]
Related, but we have other optional dependencies we may want to do this for, like `nclib`, and `slacrs`.

**Comment by zwimer** [comment]
I'll move this discussion offline and fix this bug.
