### ISSUE TITLE
Dark theme not working for Code View/ Pseudocode View

### ISSUE THREAD

**Issue by xxr0ss** [angr/angr-management#847]
### Description

When I change theme to dark theme, the syntax highlight color changes though, the background stays white.

![image](https://user-images.githubusercontent.com/31790712/207271237-4ef65638-82ed-48b8-8421-c8f507844d55.png)

### Steps to reproduce the bug

Use the dark theme and see the pseudocode.

### Environment

latest build from source

**Comment by ltfish** [comment]
It’s a known bug. We will get it fixed at some point.
