### ISSUE TITLE
Cannot use decompiler when open from .adb file because varec is not available

### ISSUE THREAD

**Issue by xxr0ss** [angr/angr-management#867]
### Description

`_analysis_configuration['varec']` is not loaded when opening a `.adb` file. I have to use some hacky method to triger it's loading.

### Steps to reproduce the bug

Save a `.adb` file and open from it.

Press F5 and error raises saying:
```
angrmanagement.data.object_container | Error raised from event of (container: The function to decompile)<Function XXX>
```

```
Traceback (most recent call last):
  File "angr-dev/angr-management\angrmanagement\data\object_container.py", line 32, in am_event
    listener(**kwargs)
  File "angr-dev/angr-management\angrmanagement\ui\views\code_view.py", line 319, in _on_new_function
    self.decompile(focus=focus, focus_addr=focus_addr, flavor=flavor)
  File "angr-dev/angr-management\angrmanagement\ui\views\code_view.py", line 151, in decompile
    options = self.instance._analysis_configuration['varec'].to_dict()
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

And current function won't get decompiled.

Press F4 or use the menu to open "Run Analysis" window and varec will be loaded, then decompiler works well.
![image](https://user-images.githubusercontent.com/31790712/210357932-80eb8637-7796-4196-be0a-f5ef957d6eb6.png)

**Comment by ltfish** [comment]
Thanks for reporting! angr db needs a lot more testing.
