### ISSUE TITLE
Using archr

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#87]
Is there any plan (and if so, timeline) to migrate angr-management to use archr internally?

Given a local binary that has related data files, env vars, etc that might be relevant to analysis, it would be helpful to have a project/target that innately includes the (pre-execution/static) state. It would also more easily expose this stuff to manipulation via the GUI.

I'm aware of the plugin for the `DockerImageTarget` but I'd be using a `LocalTarget`.

**Comment by ltfish** [comment]
archr is far from mature. I'm ok with angr management using archr as long as archr is not a mandatory requirement for installing angr management. Let's say, when I'm running `pip install angr-management`, I don't want to have the docker Python binding installed on my machine at the same time.

**Comment by sraboy** [comment]
No problem. In that case, I think I'll just do it with a plugin.
