### ISSUE TITLE
Invalid Argument in instance.py

### ISSUE THREAD

**Issue by F4lc0nCt** [angr/angr-management#9]
Hi!

Due to an update of the Angr library, the _strong_path_mapping_ argument in the function _add_path_group_ from the file [data/instance.py](https://github.com/angr/angr-management/blob/master/angrmanagement/data/instance.py) seems not to be supported anymore. By removing it, it seems to work.

**Comment by zardus** [comment]
Thanks for spotting this. angr-management has gotten a bit of attention in the last few days, and we'll push a fix with the next release!

**Comment by ltfish** [comment]
This one is already fixed internally right after the previous release. We will be making a new release soon(-ish)!

**Comment by ltfish** [comment]
I pushed the new code to GitHub yesterday. I'm closing this issue for now.

**Comment by F4lc0nCt** [comment]
Thank you. I will be able to continue to test this tool.
