### ISSUE TITLE
Odd Dock Behavior

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#98]
Ping @ananay

Ref code: https://github.com/angr/angr-management/blob/3d6d502b87b58d2adcba6461606a338672421828/angrmanagement/ui/view_manager.py#L43-L48

I want to display my plugin on the far-right, i.e., right of `DisassemblyView`. If I set its view's `default_docking_position` to left/top/bottom, behavior is as expected. If I set it to `'right'`, then the above code adds it to the central widget as a tab, like `DisassemblyView`, etc. 

The only way to have it tabbed on the right is to set `default_docking_position` to an invalid value, which means its `dock_area` gets set to `Qt.RightDockWidgetArea` and the above code will follow the second branch instead.

Here's what I want, which I can only get by calling `BaseView` with `default_docking_position='middle'`:

<img width="599" alt="angrmanagment_dock" src="https://user-images.githubusercontent.com/4247887/60095945-5eacc880-9715-11e9-968f-3017ebe6af99.png">

This works but has a downside/bug. That barrier you see between `DisassemblyView` and my `ChessPlugin` is actually two barriers, between which the "Split View" feature puts tabs and which can be resized to display a large empty area.

Here's that awkward empty space:

<img width="548" alt="empty_space" src="https://user-images.githubusercontent.com/4247887/60096323-41c4c500-9716-11e9-8836-3c8b4ee1de5c.png">

Here's a split view tab:

<img width="595" alt="tab_split" src="https://user-images.githubusercontent.com/4247887/60096329-45f0e280-9716-11e9-86b4-5cfc80176fe2.png">

I *think* the simplest solution is for `ViewManager` to expose a function to add a tab to the central area that's automatically split out to a specified size (e.g., formalize what I'm doing to get `Qt.RightDockWidgetArea` and adding the widget to the `MainWindow` rather than `central_widget`). However, the better solution might be improving support in `ViewManager` for nested & grouped docking (see Woboq's second example [here](https://woboq.com/blog/qdockwidget-changes-in-56.html)).

**Comment by ananay** [comment]
Sorry for the delay in fixing this. Thank you for fixing this @hippwndon! 🎉
