### ISSUE TITLE
angr cannot find `angr_native.so`

### ISSUE THREAD

**Issue by zwimer** [angr/angr-management#986]
### Description

The latest onefile build loads with this warning:
```
WARNING  | 2023-04-25 17:48:39,969 | angr.state_plugins.unicorn_engine | failed loading "angr_native.so", unicorn support disabled (Failed to load dynlib/dll '/tmp/_MEITmWGYk/angr/lib/lib/angr_native.so'. Most likely this dynlib/dll was not found when the application was frozen.)
```
I assume this issue is `lib/lib/` should just be `lib/`.

### Steps to reproduce the bug

Download https://github.com/angr/angr-management/releases/download/nightly/angr-management-onefile-ubuntu-22.04
`chmod +x` it
Run it

### Environment

Ubuntu 22.04

**Comment by twizmwazin** [comment]
Testing the current state of this, it seems like this is reproducible on linux and macos, but not windows.
